name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
    push:
        branches:
            - bai_23_26
jobs:
    test-ci:
        name: Test CI
        timeout-minutes: 5
        runs-on: ubuntu-latest
        permissions:
            contents: "read"
            id-token: "write"
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
<<<<<<< HEAD
              java-version: "17"
              distribution: "temurin"
              cache: maven
        - name: Install Chrome
          uses: browser-actions/setup-chrome@latest
          run: chrome --version

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: CI Test
          run: mvn clean test -Dsuite=TestNG

          # uses: actions/upload-artifact@v3
          # if: failure()
          # with:
          #     name: testng-report-${{github.run_number}}
          #     path: target/surefire-reports/emailable-report.html
